### ISSUE TITLE
How do you select the ROIS for unlabeled images from target domain ?

### ISSUE THREAD

**Issue by alexrame** [yuhuayc/da-faster-rcnn#11]
The problem is that, by definition, you do not have groud truth for unlabelled images.

However you need groudtruth
- in the definition of your blob objects, in lib.roi_data_da_layer.minibatch
- in order to select the ROIS

I do not see in the code how you made it possible... and I am trying to reproduce the paper in TF

**Comment by yuhuayc** [comment]
Hi, thanks for the message. We simply use all ROIS from rpn for the domain alignment, thus there is no selection of ROIS invoved.

**Comment by divyam02** [comment]
Hi, I was trying to implement your paper in PyTorch. Exactly how many ROIS are being used in your network? 

Target consistency regularization loss becomes very high as compared to source consistency loss due to the number of ROIS being included in the roi pooled features for target images. 

I am using https://github.com/jwyang/faster-rcnn.pytorch and applying domain adaptive elements.
